version: "3"
# Start from cmd line: docker-compose up -d
# Or directly from IntelliJ IDEA

services:
  # Works, but not maintained anymore:
  # https://github.com/vromero/activemq-artemis-docker
  # Alternative:
  # https://github.com/apache/activemq-artemis/tree/main/artemis-docker
  artemis:
    restart: always
    image: vromero/activemq-artemis:2.16.0-alpine
    hostname: artemis
    networks:
      - runtime-net
    ports:
      - "8161:8161"
      - "21616:61616"
      - "21613:61613"
      - "1199:1199"
      - "1198:1198"
    environment:
      - ENABLE_JMX=true
      - JMX_PORT=1199
      - JMX_RMI_PORT=1198

  atmoz_sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: echouser:password:::echo

  # toke/mosquitto extends eclipse-mosquitto with
  # additional Websockets, configured on port 9001
  # https://hub.docker.com/r/toke/mosquitto
  mosquitto:
    depends_on:
      - mqtt-admin
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  # https://hub.docker.com/r/dersimn/mqtt-admin
  mqtt-admin:
    image: dersimn/mqtt-admin
    ports:
      - 8090:80
    environment:
      # Connect to MQTT broker via Websockets
      - MQTT_HOST=localhost:9001

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
        - runtime-net

  broker:
    image: confluentinc/cp-kafka:6.2.4
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # https://rmoff.net/2018/08/02/kafka-listeners-explained
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - runtime-net

networks:
  runtime-net: